// Isolated no-window EGL/ANGLE + D3D12 texture-sharing proof.
#define wmain unusedNativeFixtureEntry
#include "native-dxr-fixture.cpp"
#undef wmain
#include <d3d11_4.h>
#include <EGL/egl.h>
#include <GL/glcorearb.h>
#include <filesystem>
#include <chrono>
#include <thread>

template<class T> static T load(HMODULE module,const char* name){auto value=GetProcAddress(module,name);if(!value)throw std::runtime_error(std::string("Missing export ")+name);return reinterpret_cast<T>(value);}
static double milliseconds(std::chrono::steady_clock::time_point start){return std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count();}
int wmain(int argc,wchar_t** argv){try{
    SetUnhandledExceptionFilter([](EXCEPTION_POINTERS* e)->LONG{HMODULE module{};wchar_t path[1024]{};GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS|GET_MODULE_HANDLE_EX_FLAG_UNCHANGED_REFCOUNT,reinterpret_cast<LPCWSTR>(e->ExceptionRecord->ExceptionAddress),&module);GetModuleFileNameW(module,path,1024);std::cerr<<"UNHANDLED code="<<std::hex<<e->ExceptionRecord->ExceptionCode<<" module="<<utf8(path)<<" offset="<<(reinterpret_cast<uintptr_t>(e->ExceptionRecord->ExceptionAddress)-reinterpret_cast<uintptr_t>(module))<<std::endl;return EXCEPTION_EXECUTE_HANDLER;});
    if(argc!=3)throw std::runtime_error("Arguments: chrome-library-directory output-directory");
    const std::filesystem::path libraries=argv[1],output=argv[2];std::filesystem::create_directories(output);
    SetDefaultDllDirectories(LOAD_LIBRARY_SEARCH_DEFAULT_DIRS|LOAD_LIBRARY_SEARCH_USER_DIRS);auto cookie=AddDllDirectory(libraries.c_str());if(!cookie)throw std::runtime_error("Add ANGLE directory failed");
    auto eglLibrary=LoadLibraryExW((libraries/L"libEGL.dll").c_str(),nullptr,LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR|LOAD_LIBRARY_SEARCH_DEFAULT_DIRS);
    auto glLibrary=LoadLibraryExW((libraries/L"libGLESv2.dll").c_str(),nullptr,LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR|LOAD_LIBRARY_SEARCH_DEFAULT_DIRS);
    if(!eglLibrary||!glLibrary)throw std::runtime_error("Load ANGLE libraries failed, Win32="+std::to_string(GetLastError()));
#define E(name) auto name=load<decltype(&::name)>(eglLibrary,#name)
    E(eglGetError);E(eglQueryString);E(eglGetProcAddress);E(eglInitialize);E(eglChooseConfig);E(eglCreateContext);E(eglCreatePbufferSurface);E(eglMakeCurrent);E(eglBindAPI);E(eglCreatePbufferFromClientBuffer);E(eglDestroySurface);E(eglDestroyContext);E(eglTerminate);
    auto eglCheck=[&](bool okay,const char* operation){if(!okay)throw std::runtime_error(std::string(operation)+" EGL error="+std::to_string(eglGetError()));};
    using GetPlatformDisplay=EGLDisplay(EGLAPIENTRY*)(EGLenum,void*,const EGLint*);
    auto getPlatformDisplay=reinterpret_cast<GetPlatformDisplay>(eglGetProcAddress("eglGetPlatformDisplayEXT"));if(!getPlatformDisplay)throw std::runtime_error("ANGLE platform extension absent");
    const EGLint platformAttributes[]{0x3203,0x3208,0x3209,0x320A,EGL_NONE};
    auto display=getPlatformDisplay(0x3202,EGL_DEFAULT_DISPLAY,platformAttributes);eglCheck(display!=EGL_NO_DISPLAY,"ANGLE D3D11 display");
    EGLint major=0,minor=0;eglCheck(eglInitialize(display,&major,&minor),"eglInitialize");eglCheck(eglBindAPI(EGL_OPENGL_ES_API),"Bind ES API");
    const EGLint configAttributes[]{EGL_SURFACE_TYPE,EGL_PBUFFER_BIT,EGL_RENDERABLE_TYPE,0x0040,EGL_RED_SIZE,8,EGL_GREEN_SIZE,8,EGL_BLUE_SIZE,8,EGL_ALPHA_SIZE,8,EGL_NONE};EGLConfig config{};EGLint configCount=0;eglCheck(eglChooseConfig(display,configAttributes,&config,1,&configCount)&&configCount,"ES3 config");
    const EGLint contextAttributes[]{EGL_CONTEXT_CLIENT_VERSION,3,EGL_NONE};auto context=eglCreateContext(display,config,EGL_NO_CONTEXT,contextAttributes);eglCheck(context!=EGL_NO_CONTEXT,"ES3 context");
    constexpr UINT size=64;const EGLint surfaceAttributes[]{EGL_WIDTH,size,EGL_HEIGHT,size,EGL_NONE};auto surface=eglCreatePbufferSurface(display,config,surfaceAttributes);eglCheck(surface!=EGL_NO_SURFACE,"Offscreen pbuffer");eglCheck(eglMakeCurrent(display,surface,surface,context),"Make current");
#define G(type,name) auto name=load<type>(glLibrary,#name)
    G(PFNGLGETSTRINGPROC,glGetString);G(PFNGLGETERRORPROC,glGetError);G(PFNGLGETINTEGERVPROC,glGetIntegerv);G(PFNGLCREATESHADERPROC,glCreateShader);G(PFNGLSHADERSOURCEPROC,glShaderSource);G(PFNGLCOMPILESHADERPROC,glCompileShader);G(PFNGLGETSHADERIVPROC,glGetShaderiv);G(PFNGLGETSHADERINFOLOGPROC,glGetShaderInfoLog);G(PFNGLCREATEPROGRAMPROC,glCreateProgram);G(PFNGLATTACHSHADERPROC,glAttachShader);G(PFNGLLINKPROGRAMPROC,glLinkProgram);G(PFNGLGETPROGRAMIVPROC,glGetProgramiv);G(PFNGLGETPROGRAMINFOLOGPROC,glGetProgramInfoLog);G(PFNGLUSEPROGRAMPROC,glUseProgram);G(PFNGLGENFRAMEBUFFERSPROC,glGenFramebuffers);G(PFNGLBINDFRAMEBUFFERPROC,glBindFramebuffer);G(PFNGLGENRENDERBUFFERSPROC,glGenRenderbuffers);G(PFNGLBINDRENDERBUFFERPROC,glBindRenderbuffer);G(PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC,glRenderbufferStorageMultisample);G(PFNGLFRAMEBUFFERRENDERBUFFERPROC,glFramebufferRenderbuffer);G(PFNGLCHECKFRAMEBUFFERSTATUSPROC,glCheckFramebufferStatus);G(PFNGLBLITFRAMEBUFFERPROC,glBlitFramebuffer);G(PFNGLVIEWPORTPROC,glViewport);G(PFNGLCLEARCOLORPROC,glClearColor);G(PFNGLCLEARPROC,glClear);G(PFNGLDRAWARRAYSPROC,glDrawArrays);G(PFNGLREADPIXELSPROC,glReadPixels);G(PFNGLFINISHPROC,glFinish);
    const std::string renderer=reinterpret_cast<const char*>(glGetString(GL_RENDERER)),version=reinterpret_cast<const char*>(glGetString(GL_VERSION)),extensions=eglQueryString(display,EGL_EXTENSIONS);
    std::cout<<"RENDERER "<<renderer<<" VERSION "<<version<<std::endl;if(renderer.find("RTX 3080")==std::string::npos)throw std::runtime_error("Expected RTX3080 ANGLE renderer");
    using QueryDisplay=EGLBoolean(EGLAPIENTRY*)(EGLDisplay,EGLint,intptr_t*);using QueryDevice=EGLBoolean(EGLAPIENTRY*)(void*,EGLint,intptr_t*);
    auto queryDisplay=reinterpret_cast<QueryDisplay>(eglGetProcAddress("eglQueryDisplayAttribEXT"));auto queryDevice=reinterpret_cast<QueryDevice>(eglGetProcAddress("eglQueryDeviceAttribEXT"));if(!queryDisplay||!queryDevice)throw std::runtime_error("EGL device query unavailable");intptr_t eglDevice=0,d3dDevice=0;eglCheck(queryDisplay(display,0x322C,&eglDevice),"Query EGL device");eglCheck(queryDevice(reinterpret_cast<void*>(eglDevice),0x33A1,&d3dDevice),"Query ANGLE D3D11 device");ComPtr<ID3D11Device> device11=reinterpret_cast<ID3D11Device*>(d3dDevice);ComPtr<ID3D11Device1> device11v1;check(device11.As(&device11v1),"D3D11.1 device");
    ComPtr<IDXGIDevice> dxgiDevice;check(device11.As(&dxgiDevice),"DXGI device");ComPtr<IDXGIAdapter> adapter;check(dxgiDevice->GetAdapter(&adapter),"Get same adapter");ComPtr<ID3D12Device> device12;check(D3D12CreateDevice(adapter.Get(),D3D_FEATURE_LEVEL_12_0,IID_PPV_ARGS(&device12)),"D3D12 same adapter");
    D3D12_HEAP_PROPERTIES heap{};heap.Type=D3D12_HEAP_TYPE_DEFAULT;D3D12_RESOURCE_DESC textureDesc{};textureDesc.Dimension=D3D12_RESOURCE_DIMENSION_TEXTURE2D;textureDesc.Width=size;textureDesc.Height=size;textureDesc.DepthOrArraySize=1;textureDesc.MipLevels=1;textureDesc.Format=DXGI_FORMAT_R8G8B8A8_UNORM;textureDesc.SampleDesc.Count=1;textureDesc.Flags=D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET;ComPtr<ID3D12Resource> texture12;check(device12->CreateCommittedResource(&heap,D3D12_HEAP_FLAG_SHARED,&textureDesc,D3D12_RESOURCE_STATE_COMMON,nullptr,IID_PPV_ARGS(&texture12)),"Create shared D3D12 texture");HANDLE sharedHandle{};check(device12->CreateSharedHandle(texture12.Get(),nullptr,GENERIC_ALL,nullptr,&sharedHandle),"Create shared texture handle");ComPtr<ID3D11Texture2D> texture11;check(device11v1->OpenSharedResource1(sharedHandle,IID_PPV_ARGS(&texture11)),"Open D3D12 texture in ANGLE D3D11 device");CloseHandle(sharedHandle);
    D3D12_COMMAND_QUEUE_DESC queueDesc{};queueDesc.Type=D3D12_COMMAND_LIST_TYPE_DIRECT;ComPtr<ID3D12CommandQueue> queue;check(device12->CreateCommandQueue(&queueDesc,IID_PPV_ARGS(&queue)),"Queue");ComPtr<ID3D12CommandAllocator> allocator;check(device12->CreateCommandAllocator(queueDesc.Type,IID_PPV_ARGS(&allocator)),"Allocator");ComPtr<ID3D12GraphicsCommandList> commands;check(device12->CreateCommandList(0,queueDesc.Type,allocator.Get(),nullptr,IID_PPV_ARGS(&commands)),"Commands");ComPtr<ID3D12Fence> fence;check(device12->CreateFence(0,D3D12_FENCE_FLAG_NONE,IID_PPV_ARGS(&fence)),"Fence");UINT64 fenceValue=0;
    auto wait=[&](){check(commands->Close(),"Close commands");ID3D12CommandList* list[]{commands.Get()};queue->ExecuteCommandLists(1,list);check(queue->Signal(fence.Get(),++fenceValue),"Signal");HANDLE event=CreateEventW(nullptr,FALSE,FALSE,nullptr);check(fence->SetEventOnCompletion(fenceValue,event),"Wait event");auto status=WaitForSingleObject(event,10000);CloseHandle(event);if(status!=WAIT_OBJECT_0)throw std::runtime_error("GPU timeout");check(device12->GetDeviceRemovedReason(),"Device status");check(allocator->Reset(),"Reset allocator");check(commands->Reset(allocator.Get(),nullptr),"Reset commands");};
    auto change=[&](D3D12_RESOURCE_STATES before,D3D12_RESOURCE_STATES after){D3D12_RESOURCE_BARRIER barrier{};barrier.Type=D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;barrier.Transition={texture12.Get(),D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES,before,after};commands->ResourceBarrier(1,&barrier);};
    D3D12_PLACED_SUBRESOURCE_FOOTPRINT footprint{};UINT64 textureBytes=0;device12->GetCopyableFootprints(&textureDesc,0,1,0,&footprint,nullptr,nullptr,&textureBytes);std::vector<uint8_t> initial(textureBytes);for(UINT y=0;y<size;++y)for(UINT x=0;x<size;++x){auto p=&initial[y*footprint.Footprint.RowPitch+x*4];p[0]=17;p[1]=53;p[2]=91;p[3]=255;}
    auto initialUpload=buffer(device12.Get(),textureBytes,D3D12_HEAP_TYPE_UPLOAD,D3D12_RESOURCE_STATE_GENERIC_READ);upload(initialUpload.Get(),initial.data(),initial.size());D3D12_TEXTURE_COPY_LOCATION textureLocation{};textureLocation.pResource=texture12.Get();textureLocation.Type=D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;D3D12_TEXTURE_COPY_LOCATION uploadLocation{};uploadLocation.pResource=initialUpload.Get();uploadLocation.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;uploadLocation.PlacedFootprint=footprint;change(D3D12_RESOURCE_STATE_COMMON,D3D12_RESOURCE_STATE_COPY_DEST);commands->CopyTextureRegion(&textureLocation,0,0,0,&uploadLocation,nullptr);change(D3D12_RESOURCE_STATE_COPY_DEST,D3D12_RESOURCE_STATE_COMMON);wait();
    const EGLint sharedAttributes[]{EGL_NONE};auto sharedSurface=eglCreatePbufferFromClientBuffer(display,0x33A3,reinterpret_cast<EGLClientBuffer>(texture11.Get()),config,sharedAttributes);eglCheck(sharedSurface!=EGL_NO_SURFACE,"Create surface from shared D3D11 texture");eglCheck(eglMakeCurrent(display,sharedSurface,sharedSurface,context),"Use shared surface");
    std::vector<uint8_t> pixels(size*size*4);glReadPixels(0,0,size,size,GL_RGBA,GL_UNSIGNED_BYTE,pixels.data());UINT initialMismatches=0;for(UINT i=0;i<size*size;++i)if(pixels[i*4]!=17||pixels[i*4+1]!=53||pixels[i*4+2]!=91||pixels[i*4+3]!=255)++initialMismatches;if(initialMismatches)throw std::runtime_error("D3D12 to ANGLE pixel mismatch");
    auto compile=[&](GLenum type,const char* text){GLuint shader=glCreateShader(type);glShaderSource(shader,1,&text,nullptr);glCompileShader(shader);GLint okay=0;glGetShaderiv(shader,GL_COMPILE_STATUS,&okay);if(!okay){char log[8192]{};glGetShaderInfoLog(shader,8191,nullptr,log);throw std::runtime_error(log);}return shader;};
    const char* vertex="#version 300 es\nprecision highp float; const vec2 pos[3]=vec2[3](vec2(-0.83,-0.72),vec2(0.81,-0.59),vec2(-0.16,0.86)); void main(){gl_Position=vec4(pos[gl_VertexID],0.,1.);}";
    const char* fragment="#version 300 es\nprecision highp float; out vec4 color; void main(){color=vec4(1.,0.5,0.125,1.);}";auto program=glCreateProgram();glAttachShader(program,compile(GL_VERTEX_SHADER,vertex));glAttachShader(program,compile(GL_FRAGMENT_SHADER,fragment));glLinkProgram(program);GLint linked=0;glGetProgramiv(program,GL_LINK_STATUS,&linked);if(!linked){char log[8192]{};glGetProgramInfoLog(program,8191,nullptr,log);throw std::runtime_error(log);}glUseProgram(program);
    GLint maxSamples=0;glGetIntegerv(GL_MAX_SAMPLES,&maxSamples);if(maxSamples<4)throw std::runtime_error("4x MSAA unsupported");GLuint fbo=0,colorBuffer=0;glGenFramebuffers(1,&fbo);glBindFramebuffer(GL_FRAMEBUFFER,fbo);glGenRenderbuffers(1,&colorBuffer);glBindRenderbuffer(GL_RENDERBUFFER,colorBuffer);glRenderbufferStorageMultisample(GL_RENDERBUFFER,4,GL_RGBA8,size,size);glFramebufferRenderbuffer(GL_FRAMEBUFFER,GL_COLOR_ATTACHMENT0,GL_RENDERBUFFER,colorBuffer);if(glCheckFramebufferStatus(GL_FRAMEBUFFER)!=GL_FRAMEBUFFER_COMPLETE)throw std::runtime_error("MSAA framebuffer incomplete");
    auto drawStart=std::chrono::steady_clock::now();glViewport(0,0,size,size);glClearColor(0,0,0,1);glClear(GL_COLOR_BUFFER_BIT);glDrawArrays(GL_TRIANGLES,0,3);glBindFramebuffer(GL_READ_FRAMEBUFFER,fbo);glBindFramebuffer(GL_DRAW_FRAMEBUFFER,0);glBlitFramebuffer(0,0,size,size,0,0,size,size,GL_COLOR_BUFFER_BIT,GL_NEAREST);glFinish();const double drawWall=milliseconds(drawStart);glBindFramebuffer(GL_FRAMEBUFFER,0);glReadPixels(0,0,size,size,GL_RGBA,GL_UNSIGNED_BYTE,pixels.data());const auto glError=glGetError();if(glError)throw std::runtime_error("GL error="+std::to_string(glError));UINT full=0,partial=0,empty=0;for(UINT i=0;i<size*size;++i){if(pixels[i*4]==255)++full;else if(pixels[i*4]>0)++partial;else ++empty;}if(!full||!partial||!empty)throw std::runtime_error("MSAA coverage fixture did not exercise full, partial and empty samples");
    eglCheck(eglMakeCurrent(display,surface,surface,context),"Release shared surface");ComPtr<ID3D11DeviceContext> context11;device11->GetImmediateContext(&context11);context11->Flush();D3D11_QUERY_DESC queryDesc{D3D11_QUERY_EVENT,0};ComPtr<ID3D11Query> completed;check(device11->CreateQuery(&queryDesc,&completed),"D3D11 event");context11->End(completed.Get());context11->Flush();const auto syncStart=std::chrono::steady_clock::now();while(context11->GetData(completed.Get(),nullptr,0,0)==S_FALSE){if(milliseconds(syncStart)>10000)throw std::runtime_error("D3D11 completion timeout");std::this_thread::sleep_for(std::chrono::milliseconds(1));}
    auto readback=buffer(device12.Get(),textureBytes,D3D12_HEAP_TYPE_READBACK,D3D12_RESOURCE_STATE_COPY_DEST);D3D12_TEXTURE_COPY_LOCATION readLocation{};readLocation.pResource=readback.Get();readLocation.Type=D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;readLocation.PlacedFootprint=footprint;change(D3D12_RESOURCE_STATE_COMMON,D3D12_RESOURCE_STATE_COPY_SOURCE);commands->CopyTextureRegion(&readLocation,0,0,0,&textureLocation,nullptr);change(D3D12_RESOURCE_STATE_COPY_SOURCE,D3D12_RESOURCE_STATE_COMMON);wait();uint8_t* mapped{};D3D12_RANGE readRange{0,SIZE_T(textureBytes)};check(readback->Map(0,&readRange,reinterpret_cast<void**>(&mapped)),"Map D3D12 result");UINT mismatches=0,flippedMismatches=0;for(UINT y=0;y<size;++y)for(UINT x=0;x<size;++x){if(memcmp(mapped+y*footprint.Footprint.RowPitch+x*4,pixels.data()+(y*size+x)*4,4))++mismatches;if(memcmp(mapped+y*footprint.Footprint.RowPitch+x*4,pixels.data()+((size-1-y)*size+x)*4,4))++flippedMismatches;}D3D12_RANGE noWrite{0,0};readback->Unmap(0,&noWrite);const bool exact=mismatches==0||flippedMismatches==0;if(!exact)throw std::runtime_error("ANGLE to D3D12 shared pixels mismatch");
    #include "native-angle-formats.inc"
    #include "native-angle-bytes.inc"
    std::ofstream rgba(output/L"triangle.rgba",std::ios::binary);rgba.write(reinterpret_cast<char*>(pixels.data()),pixels.size());rgba.close();std::ofstream report(output/L"report.json");report<<std::setprecision(12)<<"{\n\"scope\":\"No-window offscreen ANGLE GLES3 4xMSAA and same-resource D3D12/D3D11 texture sharing fixture, not game performance\",\n\"renderer\":\""<<escaped(renderer)<<"\",\"version\":\""<<escaped(version)<<"\",\"eglVersion\":\""<<major<<"."<<minor<<"\",\n\"extensions\":\""<<escaped(extensions)<<"\",\n\"width\":64,\"height\":64,\"samples\":4,\"maxSamples\":"<<maxSamples<<",\"glError\":"<<glError<<",\"drawResolveFinishWallMs\":"<<drawWall<<",\n\"d3d12ToAnglePixelMismatches\":"<<initialMismatches<<",\"angleToD3d12PixelMismatches\":"<<mismatches<<",\"angleToD3d12FlippedPixelMismatches\":"<<flippedMismatches<<",\"sharedPixelsExactWithOrientation\":"<<(exact?"true":"false")<<",\n\"fullCoveragePixels\":"<<full<<",\"partialCoveragePixels\":"<<partial<<",\"emptyPixels\":"<<empty<<",\n\"cpuTransferBetweenApis\":false,\"cpuFenceSynchronization\":true,\"windowCreated\":false,\"passed\":true,\"errors\":[]\n}\n";completed.Reset();context11.Reset();eglMakeCurrent(display,EGL_NO_SURFACE,EGL_NO_SURFACE,EGL_NO_CONTEXT);eglDestroySurface(display,sharedSurface);eglDestroySurface(display,surface);eglDestroyContext(display,context);texture11.Reset();device11v1.Reset();dxgiDevice.Reset();adapter.Reset();device11.Reset();eglTerminate(display);std::cout<<"PASS sharedPixelsExact orientationFlip="<<(flippedMismatches==0)<<" partialMSAApixels="<<partial<<std::endl;return 0;
}catch(const std::exception& error){std::cerr<<error.what()<<std::endl;return 1;}}
